### ISSUE TITLE
Consider setting up a CryptoNet org on github.

### ISSUE THREAD

**Issue by jwdonahue** [itbackyard/CryptoNet#99]
They have a free tier for mostly public orgs.

https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/about-organizations

This might be a good time to set it up. Fork the version3 branch, when we get close to being done with it, to light up the first repo.

**Comment by maythamfahmi** [comment]
It is indeed a good idea-

**Comment by maythamfahmi** [comment]
@jwdonahue are you able to assist, we could eventully set a team meeting up and  peer doing it, if you like so.

do you know if current github project is portable for already starred and watchers?

**Comment by jwdonahue** [comment]
You would have to start by creating the org, add contributors to it, and then transfer ownership of the repo to that org:

https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

According the [What's transferred](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#whats-transferred-with-a-repository), pull requests, wiki, starts and watchers are also transferred.

There's some limitations that you should be aware of, so read that entire document, before you begin.

**Comment by maythamfahmi** [comment]
organization created https://github.com/[itbackyard](https://github.com/itbackyard)

**Comment by maythamfahmi** [comment]
successfully transferred to https://github.com/itbackyard/CryptoNet
